Name:           ros-indigo-moveit-pr2
Version:        0.6.5
Release:        0%{?dist}
Summary:        ROS moveit_pr2 package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-pr2-moveit-config
Requires:       ros-indigo-pr2-moveit-plugins
Requires:       ros-indigo-pr2-moveit-tutorials
BuildRequires:  ros-indigo-catkin

%description
All PR2-specific packages for MoveIt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Jun 23 2017 Ioan Sucan <isucan@willowgarage.com> - 0.6.5-0
- Autogenerated by Bloom

* Fri Feb 05 2016 Ioan Sucan <isucan@willowgarage.com> - 0.6.2-0
- Autogenerated by Bloom

* Fri Jan 16 2015 Ioan Sucan <isucan@willowgarage.com> - 0.6.1-0
- Autogenerated by Bloom

* Wed Jan 14 2015 Ioan Sucan <isucan@willowgarage.com> - 0.6.0-0
- Autogenerated by Bloom

