Name:           ros-kinetic-pr2-moveit-plugins
Version:        0.7.0
Release:        2%{?dist}
Summary:        ROS pr2_moveit_plugins package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-angles
Requires:       ros-kinetic-control-msgs
Requires:       ros-kinetic-eigen-conversions
Requires:       ros-kinetic-kdl-parser
Requires:       ros-kinetic-moveit-core
Requires:       ros-kinetic-pluginlib
Requires:       ros-kinetic-pr2-controllers-msgs
Requires:       ros-kinetic-pr2-mechanism-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-tf-conversions
Requires:       ros-kinetic-urdf
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-angles
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  ros-kinetic-control-msgs
BuildRequires:  ros-kinetic-eigen-conversions
BuildRequires:  ros-kinetic-kdl-parser
BuildRequires:  ros-kinetic-moveit-core
BuildRequires:  ros-kinetic-pluginlib
BuildRequires:  ros-kinetic-pr2-controllers-msgs
BuildRequires:  ros-kinetic-pr2-mechanism-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-tf-conversions
BuildRequires:  ros-kinetic-urdf

%description
PR2 specific plugins for MoveIt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Apr 28 2018 Bence Magyar <bence.magyar.robotics@gmail.com> - 0.7.0-2
- Autogenerated by Bloom

* Fri Apr 27 2018 Bence Magyar <bence.magyar.robotics@gmail.com> - 0.7.0-1
- Autogenerated by Bloom

* Fri Apr 27 2018 Bence Magyar <bence.magyar.robotics@gmail.com> - 0.7.0-0
- Autogenerated by Bloom

